---
- hosts: all
  remote_user: ec2-user
  gather_facts: False
  tasks:
    - name: nginx repo
      yum_repository:
        name: nginx-1.12.1-1.el7.ngx.x86_64.rpm
        description: Nginx
        baseurl: http://nginx.org/packages/centos/7/x86_64/RPMS/
        gpgcheck: no
    - name: Install Nginx
      yum: name=nginx-1.12.1-1.el7.ngx.x86_64.rpm state=present
    - name: Write nginx.conf.j2 configuration file
      template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf
    - name: Ensure Nginx is running
      service: name=nginx state=started enabled=yes
    - name: Creates ssl directory
      file: path=/etc/nginx/ssl state=directory
    - name: create self-signed SSL cert
      command: openssl req -new -nodes -x509 -subj "/C=US/ST=PA/L=PHL/O=COMCAST/CN=DEVOPS" -days 365 -keyout /etc/nginx/ssl/myserver.key -out /etc/nginx/ssl/myserver.crt
